<?php

namespace Modules\Pharma\database\seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;
use Carbon\Carbon;

class MedicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Map names to IDs for related tables
        $categories     = DB::table('medicine_categories')->pluck('id', 'name')->toArray();
        $forms          = DB::table('medicine_forms')->pluck('id', 'name')->toArray();
        $manufacturers  = DB::table('manufacturers')->pluck('id', 'name')->toArray();

        // Suppliers: map by full name
        $suppliers = DB::table('suppliers')
            ->select('id', 'first_name', 'last_name')
            ->get()
            ->reduce(function ($carry, $item) {
                $carry[trim($item->first_name . ' ' . $item->last_name)] = $item->id;
                return $carry;
            }, []);

        // Pharma users: map by first_name
        $pharmas = User::where('user_type', 'pharma')
            ->pluck('id', 'first_name')
            ->toArray();

        // Medicines data (active + expired)
        $rows = [
            // Active medicines
            [
                'name'            => 'Paracetamol',
                'dosage'          => '500mg',
                'category'        => 'Analgesics',
                'form'            => 'Tablet',
                'note'            => 'Safe for most patients; avoid exceeding daily dose.',
                'pharma'          => 'Peter',
                'supplier'        => 'Michael Scott',
                'contact_number'  => '212 555-0150',
                'payment_terms'   => '30',
                'batch_no'        => 'BATCH-0123A',
                'start_serial_no' => 'SN-0001',
                'end_serial_no'   => 'SN-0200',
                'quantity'        => 200,
                'manufacturer'    => 'PharmaCo',
                'expiry'          => '25-11-2027',
                're_order_level'  => 50,
                'purchase_price'  => 2.50,
                'selling_price'   => 5.00,
                'is_inclusive_tax' => true,
                'stock_value'     => 1000,
            ],
            [
                'name'            => 'Amoxicillin',
                'dosage'          => '250mg',
                'category'        => 'Antibiotics',
                'form'            => 'Syrup',
                'note'            => 'Complete the full course of treatment.',
                'pharma'          => 'Emily',
                'supplier'        => 'Olivia Chen',
                'contact_number'  => '404 555-0165',
                'payment_terms'   => '45',
                'batch_no'        => 'BATCH-0456B',
                'start_serial_no' => 'SN-0201',
                'end_serial_no'   => 'SN-0300',
                'quantity'        => 100,
                'manufacturer'    => 'MedCare',
                'expiry'          => '25-11-2026',
                're_order_level'  => 30,
                'purchase_price'  => 8.75,
                'selling_price'   => 15.50,
                'is_inclusive_tax' => false,
                'stock_value'     => 1550,
            ],
            [
                'name'            => 'Amlodipine',
                'dosage'          => '10mg',
                'category'        => 'Antihypertensives',
                'form'            => 'Tablet',
                'note'            => 'Take at the same time each day.',
                'pharma'          => 'Michael',
                'supplier'        => 'David Rodriguez',
                'contact_number'  => '800 555-0172',
                'payment_terms'   => '60',
                'batch_no'        => 'BATCH-0789C',
                'start_serial_no' => 'SN-0301',
                'end_serial_no'   => 'SN-0350',
                'quantity'        => 50,
                'manufacturer'    => 'PharmaCo',
                'expiry'          => '18-02-2028',
                're_order_level'  => 25,
                'purchase_price'  => 4.20,
                'selling_price'   => 8.40,
                'is_inclusive_tax' => true,
                'stock_value'     => 420,
            ],
            [
                'name'            => 'Cetirizine',
                'dosage'          => '10mg',
                'category'        => 'Antihistamines',
                'form'            => 'Tablet',
                'note'            => 'May cause drowsiness.',
                'pharma'          => 'Sarah',
                'supplier'        => 'Emily Hayes',
                'contact_number'  => '650 555-0188',
                'payment_terms'   => '40',
                'batch_no'        => 'BATCH-1011D',
                'start_serial_no' => 'SN-0351',
                'end_serial_no'   => 'SN-0400',
                'quantity'        => 50,
                'manufacturer'    => 'BioGen',
                'expiry'          => '25-05-2027',
                're_order_level'  => 40,
                'purchase_price'  => 3.10,
                'selling_price'   => 6.20,
                'is_inclusive_tax' => false,
                'stock_value'     => 310,
            ],
            [
                'name'            => 'Simvastatin',
                'dosage'          => '40mg',
                'category'        => 'Cardiovascular',
                'form'            => 'Tablet',
                'note'            => 'Used to lower cholesterol.',
                'pharma'          => 'Emily',
                'supplier'        => 'Olivia Chen',
                'contact_number'  => '404 555-0165',
                'payment_terms'   => '45',
                'batch_no'        => 'BATCH-1415F',
                'start_serial_no' => 'SN-0451',
                'end_serial_no'   => 'SN-0500',
                'quantity'        => 50,
                'manufacturer'    => 'BioGen',
                'expiry'          => '15-06-2027',
                're_order_level'  => 35,
                'purchase_price'  => 6.50,
                'selling_price'   => 12.00,
                'is_inclusive_tax' => true,
                'stock_value'     => 600,
            ],
            [
                'name'            => 'Atorvastatin',
                'dosage'          => '20mg',
                'category'        => 'Cardiovascular',
                'form'            => 'Tablet',
                'note'            => 'Not recommended for pregnant women.',
                'pharma'          => 'Emily',
                'supplier'        => 'David Rodriguez',
                'contact_number'  => '800 555-0172',
                'payment_terms'   => '60',
                'batch_no'        => 'BATCH-1617G',
                'start_serial_no' => 'SN-0501',
                'end_serial_no'   => 'SN-0600',
                'quantity'        => 100,
                'manufacturer'    => 'PharmaCo',
                'expiry'          => '25-04-2027',
                're_order_level'  => 50,
                'purchase_price'  => 5.30,
                'selling_price'   => 10.50,
                'is_inclusive_tax' => false,
                'stock_value'     => 1050,
            ],
            [
                'name'            => 'Ibuprofen',
                'dosage'          => '200mg',
                'category'        => 'Analgesics',
                'form'            => 'Tablet',
                'note'            => 'Take with food or milk to avoid stomach upset.',
                'pharma'          => 'Sarah',
                'supplier'        => 'Emily Hayes',
                'contact_number'  => '650 555-0188',
                'payment_terms'   => '40',
                'batch_no'        => 'BATCH-1819H',
                'start_serial_no' => 'SN-0601',
                'end_serial_no'   => 'SN-0670',
                'quantity'        => 70,
                'manufacturer'    => 'MedCare',
                'expiry'          => '30-10-2026',
                're_order_level'  => 75,
                'purchase_price'  => 1.80,
                'selling_price'   => 3.50,
                'is_inclusive_tax' => false,
                'stock_value'     => 245,
            ],
            [
                'name'            => 'Lisinopril',
                'dosage'          => '10mg',
                'category'        => 'Antihypertensives',
                'form'            => 'Tablet',
                'note'            => 'Not for use during pregnancy.',
                'pharma'          => 'Peter',
                'supplier'        => 'Michael Scott',
                'contact_number'  => '212 555-0150',
                'payment_terms'   => '30',
                'batch_no'        => 'BATCH-2021I',
                'start_serial_no' => 'SN-0671',
                'end_serial_no'   => 'SN-0750',
                'quantity'        => 80,
                'manufacturer'    => 'PharmaCo',
                'expiry'          => '20-03-2027',
                're_order_level'  => 40,
                'purchase_price'  => 4.15,
                'selling_price'   => 8.25,
                'is_inclusive_tax' => false,
                'stock_value'     => 660,
            ],
            [
                'name'            => 'Salbutamol',
                'dosage'          => '100mcg',
                'category'        => 'Respiratory',
                'form'            => 'Inhaler',
                'note'            => 'For asthma and COPD.',
                'pharma'          => 'Peter',
                'supplier'        => 'Olivia Chen',
                'contact_number'  => '404 555-0165',
                'payment_terms'   => '45',
                'batch_no'        => 'BATCH-2223J',
                'start_serial_no' => 'SN-0751',
                'end_serial_no'   => 'SN-0810',
                'quantity'        => 60,
                'manufacturer'    => 'BioGen',
                'expiry'          => '20-05-2028',
                're_order_level'  => 20,
                'purchase_price'  => '$11',
                'selling_price'   => '$22.50',
                'tax'             => '',
                'stock_value'     => '$1,350',
            ],
            [
                'name'            => 'Warfarin',
                'dosage'          => '5mg',
                'category'        => 'Anticoagulants',
                'form'            => 'Tablet',
                'note'            => 'Requires regular blood tests to monitor.',
                'pharma'          => 'Peter',
                'supplier'        => 'Emily Hayes',
                'contact_number'  => '650 555-0188',
                'payment_terms'   => '40',
                'batch_no'        => 'BATCH-2627L',
                'start_serial_no' => 'SN-0851',
                'end_serial_no'   => 'SN-0930',
                'quantity'        => 80,
                'manufacturer'    => 'MedCare',
                'expiry'          => '21-03-2029',
                're_order_level'  => 20,
                'purchase_price'  => '$9.20',
                'selling_price'   => '$18.50',
                'tax'             => '',
                'stock_value'     => '$1,480',
            ],
            [
                'name'            => 'Levothyroxine',
                'dosage'          => '50mcg',
                'category'        => 'Hormones',
                'form'            => 'Tablet',
                'note'            => 'Take on an empty stomach, at least 30 minutes before food.',
                'pharma'          => 'Sarah',
                'supplier'        => 'Michael Scott',
                'contact_number'  => '212 555-0150',
                'payment_terms'   => '30',
                'batch_no'        => 'BATCH-2829M',
                'start_serial_no' => 'SN-0931',
                'end_serial_no'   => 'SN-0990',
                'quantity'        => 60,
                'manufacturer'    => 'BioGen',
                'expiry'          => '18-09-2027',
                're_order_level'  => 45,
                'purchase_price'  => 6.80,
                'selling_price'   => 13.50,
                'is_inclusive_tax' => false,
                'stock_value'     => 810,
            ],
            [
                'name'            => 'Metoprolol',
                'dosage'          => '50mg',
                'category'        => 'Cardiovascular',
                'form'            => 'Tablet',
                'note'            => 'Do not stop taking this medication abruptly.',
                'pharma'          => 'Sarah',
                'supplier'        => 'Olivia Chen',
                'contact_number'  => '404 555-0165',
                'payment_terms'   => '45',
                'batch_no'        => 'BATCH-3031N',
                'start_serial_no' => 'SN-0991',
                'end_serial_no'   => 'SN-1040',
                'quantity'        => 50,
                'manufacturer'    => 'PharmaCo',
                'expiry'          => '25-06-2028',
                're_order_level'  => 30,
                'purchase_price'  => 5.90,
                'selling_price'   => 11.80,
                'is_inclusive_tax' => true,
                'stock_value'     => 590,
            ],
            [
                'name'            => 'Furosemide',
                'dosage'          => '40mg',
                'category'        => 'Diuretics',
                'form'            => 'Tablet',
                'note'            => 'Increases urination, take in the morning.',
                'pharma'          => 'Sarah',
                'supplier'        => 'David Rodriguez',
                'contact_number'  => '800 555-0172',
                'payment_terms'   => '60',
                'batch_no'        => 'BATCH-3233O',
                'start_serial_no' => 'SN-1041',
                'end_serial_no'   => 'SN-1090',
                'quantity'        => 50,
                'manufacturer'    => 'Global Pharma',
                'expiry'          => '14-04-2027',
                're_order_level'  => 25,
                'purchase_price'  => 2.10,
                'selling_price'   => 4.20,
                'is_inclusive_tax' => false,
                'stock_value'     => 252,
            ],

            // Expired medicines
            [
                'name'            => 'Metformin',
                'dosage'          => '500mg',
                'category'        => 'Antidiabetics',
                'form'            => 'Tablet',
                'note'            => 'Take with meals to reduce stomach upset.',
                'pharma'          => 'Peter',
                'supplier'        => 'David Rodriguez',
                'contact_number'  => '800 555-0172',
                'payment_terms'   => '60',
                'batch_no'        => 'BATCH-2425K',
                'start_serial_no' => 'SN-0811',
                'end_serial_no'   => 'SN-0850',
                'quantity'        => 40,
                'manufacturer'    => 'Global Pharma',
                'expiry'          => '18-07-2025',
                're_order_level'  => 60,
                'purchase_price'  => 3.50,
                'selling_price'   => 7.00,
                'is_inclusive_tax' => true,
                'stock_value'     => 280,
            ],
            [
                'name'            => 'Omeprazole',
                'dosage'          => '20mg',
                'category'        => 'Gastrointestinal Agents',
                'form'            => 'Capsule',
                'note'            => 'Take before a meal.',
                'pharma'          => 'Peter',
                'supplier'        => 'Michael Scott',
                'contact_number'  => '212 555-0150',
                'payment_terms'   => '30',
                'batch_no'        => 'BATCH-1213E',
                'start_serial_no' => 'SN-0401',
                'end_serial_no'   => 'SN-0450',
                'quantity'        => 50,
                'manufacturer'    => 'MedCare',
                'expiry'          => '22-07-2025',
                're_order_level'  => 60,
                'purchase_price'  => 7.80,
                'selling_price'   => 14.90,
                'is_inclusive_tax' => false,
                'stock_value'     => 745,
            ],
        ];

        $data = [];

        foreach ($rows as $row) {
            $categoryId    = $categories[$row['category']]      ?? null;
            $formId        = $forms[$row['form']]               ?? null;
            $manufacturerId = $manufacturers[$row['manufacturer']] ?? null;
            $supplierId    = $suppliers[$row['supplier']]       ?? null;
            $pharmaId      = $pharmas[$row['pharma']]           ?? null;

            if (! $categoryId || ! $formId || ! $manufacturerId || ! $supplierId || ! $pharmaId) {
                continue;
            }

            $expiry = Carbon::createFromFormat('d-m-Y', $row['expiry'])->endOfDay();

            $data[] = [
                'name'            => $row['name'],
                'dosage'          => $row['dosage'],
                'pharma_id'       => $pharmaId,
                'category_id'     => $categoryId,
                'form_id'         => $formId,
                'expiry_date'     => $expiry,
                'note'            => $row['note'],
                'supplier_id'     => $supplierId,
                'contact_number'  => $row['contact_number'],
                'payment_terms'   => $row['payment_terms'],
                'quntity'         => $row['quantity'],
                're_order_level'  => $row['re_order_level'],
                'manufacturer_id' => $manufacturerId,
                'batch_no'        => $row['batch_no'],
                'start_serial_no' => $row['start_serial_no'],
                'end_serial_no'   => $row['end_serial_no'],
                'purchase_price'  => $row['purchase_price'],
                'selling_price'   => $row['selling_price'],
                'stock_value'     => $row['stock_value'],
                'is_inclusive_tax' => !empty($row['is_inclusive_tax']) ? 1 : 0,
                'created_at'      => now(),
                'updated_at'      => now(),
            ];
        }

        if (! empty($data)) {
            DB::table('medicines')->insert($data);
        }
    }
}
